In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [4]:
data=pd.read_csv("/content/ratings_sample.csv")
data

,user_id,movie_id,rating,genres,production_companies,production_countries,release_year,overview
0,93787,gods+and+monsters+1998,4,Drama,Lions Gate Films Flashpoint (I) Showtime Networks,United Kingdom United States of America,1998.0,"It's 1957, and Whale's heyday as the director ..."
1,197858,stargate+1994,3,Action Adventure Science Fiction,Centropolis Entertainment StudioCanal Carolco ...,France United States of America,1994.0,"An interstellar teleportation device, found in..."
2,76204,toy+story+1995,3,Animation Comedy Family,Pixar Animation Studios,United States of America,1995.0,"Led by Woody, Andy's toys live happily in his ..."
3,667201,friends+with+benefits+2011,4,Romance Comedy,Castle Rock Entertainment Screen Gems Olive Br...,United States of America,2011.0,Jamie is a New York-based executive recruiter ...
4,336750,sleeper+1973,4,Comedy Romance Science Fiction,Rollins-Joffe Productions,United States of America,1973.0,"Miles Monroe, a clarinet-playing health food s..."
...,...,...,...,...,...,...,...,...
1993,584138,the+matrix+revolutions+2003,3,Adventure Action Thriller Science Fiction,Village Roadshow Pictures NPV Entertainment Si...,United States of America Australia,2003.0,The human city of Zion defends itself against ...
1994,440326,koyaanisqatsi+1982,5,Documentary Music,IRE Productions Santa Fe Institute for Regiona...,United States of America,1982.0,Takes us to locations all around the US and sh...
1995,5132,prt--porter+1994,3,Drama Comedy,Miramax Films,United States of America,1994.0,Paris Fashion Week draws the usual bunch of pe...
1996,764247,clue+1985,5,Comedy Thriller Crime Mystery,Paramount Pictures Debra Hill Productions Poly...,United States of America,1985.0,Clue finds six colorful dinner guests gathered...
1997,858562,pulp+fiction+1994,4,Thriller Crime,Miramax Films A Band Apart Jersey Films,United States of America,1994.0,"A burger-loving hit man, his philosophical par..."

In [5]:
print(data.head)
print(data.tail)

<bound method NDFrame.head of       user_id                     movie_id  rating  \
0       93787       gods+and+monsters+1998       4
1      197858                stargate+1994       3
2       76204               toy+story+1995       3
3      667201   friends+with+benefits+2011       4
4      336750                 sleeper+1973       4
...       ...                          ...     ...
1993   584138  the+matrix+revolutions+2003       3
1994   440326           koyaanisqatsi+1982       5
1995     5132             prt--porter+1994       3
1996   764247                    clue+1985       5
1997   858562            pulp+fiction+1994       4

                                         genres  \
0                                         Drama
1              Action Adventure Science Fiction
2                       Animation Comedy Family
3                                Romance Comedy
4                Comedy Romance Science Fiction
...                                         ...
1993  Adventure Action Thriller Science Fiction
1994                          Documentary Music
1995                               Drama Comedy
1996              Comedy Thriller Crime Mystery
1997                             Thriller Crime

                                   production_companies  \
0     Lions Gate Films Flashpoint (I) Showtime Networks
1     Centropolis Entertainment StudioCanal Carolco ...
2                               Pixar Animation Studios
3     Castle Rock Entertainment Screen Gems Olive Br...
4                             Rollins-Joffe Productions
...                                                 ...
1993  Village Roadshow Pictures NPV Entertainment Si...
1994  IRE Productions Santa Fe Institute for Regiona...
1995                                      Miramax Films
1996  Paramount Pictures Debra Hill Productions Poly...
1997            Miramax Films A Band Apart Jersey Films

                         production_countries  release_year  \
0     United Kingdom United States of America        1998.0
1             France United States of America        1994.0
2                    United States of America        1995.0
3                    United States of America        2011.0
4                    United States of America        1973.0
...                                       ...           ...
1993       United States of America Australia        2003.0
1994                 United States of America        1982.0
1995                 United States of America        1994.0
1996                 United States of America        1985.0
1997                 United States of America        1994.0

                                               overview
0     It's 1957, and Whale's heyday as the director ...
1     An interstellar teleportation device, found in...
2     Led by Woody, Andy's toys live happily in his ...
3     Jamie is a New York-based executive recruiter ...
4     Miles Monroe, a clarinet-playing health food s...
...                                                 ...
1993  The human city of Zion defends itself against ...
1994  Takes us to locations all around the US and sh...
1995  Paris Fashion Week draws the usual bunch of pe...
1996  Clue finds six colorful dinner guests gathered...
1997  A burger-loving hit man, his philosophical par...

[1998 rows x 8 columns]>
<bound method NDFrame.tail of       user_id                     movie_id  rating  \
0       93787       gods+and+monsters+1998       4
1      197858                stargate+1994       3
2       76204               toy+story+1995       3
3      667201   friends+with+benefits+2011       4
4      336750                 sleeper+1973       4
...       ...                          ...     ...
1993   584138  the+matrix+revolutions+2003       3
1994   440326           koyaanisqatsi+1982       5
1995     5132             prt--porter+1994       3
1996   764247                    clue+1985       5
1997   858562            pulp+fiction+1994       4

                                         genres  \
0                                         Drama
1              Action Adventure Science Fiction
2                       Animation Comedy Family
3                                Romance Comedy
4                Comedy Romance Science Fiction
...                                         ...
1993  Adventure Action Thriller Science Fiction
1994                          Documentary Music
1995                               Drama Comedy
1996              Comedy Thriller Crime Mystery
1997                             Thriller Crime

                                   production_companies  \
0     Lions Gate Films Flashpoint (I) Showtime Networks
1     Centropolis Entertainment StudioCanal Carolco ...
2                               Pixar Animation Studios
3     Castle Rock Entertainment Screen Gems Olive Br...
4                             Rollins-Joffe Productions
...                                                 ...
1993  Village Roadshow Pictures NPV Entertainment Si...
1994  IRE Productions Santa Fe Institute for Regiona...
1995                                      Miramax Films
1996  Paramount Pictures Debra Hill Productions Poly...
1997            Miramax Films A Band Apart Jersey Films

                         production_countries  release_year  \
0     United Kingdom United States of America        1998.0
1             France United States of America        1994.0
2                    United States of America        1995.0
3                    United States of America        2011.0
4                    United States of America        1973.0
...                                       ...           ...
1993       United States of America Australia        2003.0
1994                 United States of America        1982.0
1995                 United States of America        1994.0
1996                 United States of America        1985.0
1997                 United States of America        1994.0

                                               overview
0     It's 1957, and Whale's heyday as the director ...
1     An interstellar teleportation device, found in...
2     Led by Woody, Andy's toys live happily in his ...
3     Jamie is a New York-based executive recruiter ...
4     Miles Monroe, a clarinet-playing health food s...
...                                                 ...
1993  The human city of Zion defends itself against ...
1994  Takes us to locations all around the US and sh...
1995  Paris Fashion Week draws the usual bunch of pe...
1996  Clue finds six colorful dinner guests gathered...
1997  A burger-loving hit man, his philosophical par...

[1998 rows x 8 columns]>

In [6]:
print(data.columns)

Index(['user_id', 'movie_id', 'rating', 'genres', 'production_companies',
       'production_countries', 'release_year', 'overview'],
      dtype='object')

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1998 entries, 0 to 1997
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   user_id               1998 non-null   int64
 1   movie_id              1998 non-null   object
 2   rating                1998 non-null   int64
 3   genres                1996 non-null   object
 4   production_companies  1985 non-null   object
 5   production_countries  1994 non-null   object
 6   release_year          1998 non-null   float64
 7   overview              1997 non-null   object
dtypes: float64(1), int64(2), object(5)
memory usage: 125.0+ KB

In [13]:
data.isnull().sum()

user_id                  0
movie_id                 0
rating                   0
genres                   2
production_companies    13
production_countries     4
release_year             0
overview                 1
dtype: int64

In [16]:
data['genres']=data['genres'].fillna('Drama')
data['production_companies']=data['production_companies'].fillna('Pixar Animation Studios')
#data['genres']=data['genres'].fillna('Drama')

In [17]:
data.isnull().sum()

user_id                 0
movie_id                0
rating                  0
genres                  0
production_companies    0
production_countries    4
release_year            0
overview                1
dtype: int64

In [8]:
data.describe()

             user_id       rating  release_year
count    1998.000000  1998.000000   1998.000000
mean   497375.253253     3.675676   1991.538539
std    290588.824443     1.056216     13.153585
min        56.000000     1.000000   1922.000000
25%    239382.000000     3.000000   1990.000000
50%    490846.000000     4.000000   1995.000000
75%    747196.750000     4.000000   1999.000000
max    998652.000000     5.000000   2014.000000

In [19]:
dependent_variable = ['release_year',]
independent_variables = ['rating']

train_data, test_data = train_test_split(data, test_size=0.2, random_state=42)

X_train = train_data[independent_variables]
y_train = train_data[dependent_variable]

X_test = test_data[independent_variables]
y_test = test_data[dependent_variable]

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [22]:
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print('Mean Squared Error:', mse)
print('Mean Absolute Error:', mae)
print('R2 Score:', r2)

Mean Squared Error: 151.03843090653785
Mean Absolute Error: 8.44081630683899
R2 Score: 0.00915507250573333